// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lxcn_asset_tracking_efc.Data;

#nullable disable

namespace lxcnassettrackingefc.Migrations
{
    [DbContext(typeof(AssetTrackingContext))]
    [Migration("20250616071910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lxcn_asset_tracking_efc.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OfficeLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PurchasePriceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchasePriceId");

                    b.ToTable("Assets");

                    b.HasDiscriminator().HasValue("Asset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("lxcn_asset_tracking_efc.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("lxcn_asset_tracking_efc.Models.Computer", b =>
                {
                    b.HasBaseType("lxcn_asset_tracking_efc.Models.Asset");

                    b.HasDiscriminator().HasValue("Computer");
                });

            modelBuilder.Entity("lxcn_asset_tracking_efc.Models.Phone", b =>
                {
                    b.HasBaseType("lxcn_asset_tracking_efc.Models.Asset");

                    b.HasDiscriminator().HasValue("Phone");
                });

            modelBuilder.Entity("lxcn_asset_tracking_efc.Models.Asset", b =>
                {
                    b.HasOne("lxcn_asset_tracking_efc.Models.Price", "PurchasePrice")
                        .WithMany()
                        .HasForeignKey("PurchasePriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchasePrice");
                });
#pragma warning restore 612, 618
        }
    }
}
